Repository googleworkspace/google-chat-samples, pull requests merged in 2024-10, with the labels that each got.

#303 Feat: Adds v2 Rolodex Chat app
  apps-script/contact-form-app/appsscript.json
  apps-script/contact-form-app/contactForm.gs
  apps-script/contact-form-app/main.gs
  apps-script/dialogs/dialogs.gs
Labels: javascript

#317 fix: prompts
  node/ai-knowledge-assistant/controllers/app.js
  node/ai-knowledge-assistant/controllers/event-app.js
  node/ai-knowledge-assistant/deploy.sh
  node/ai-knowledge-assistant/env.js
  node/ai-knowledge-assistant/events_index.js
  node/ai-knowledge-assistant/http_index.js
  node/ai-knowledge-assistant/services/aip-service.js
  node/ai-knowledge-assistant/services/app-auth-chat-service.js
  node/ai-knowledge-assistant/services/app-auth-events-service.js
  node/ai-knowledge-assistant/services/firestore-service.js
  node/ai-knowledge-assistant/services/user-auth-chat-service.js
  node/ai-knowledge-assistant/services/user-auth-events-service.js
  node/ai-knowledge-assistant/services/user-auth.js
  node/ai-knowledge-assistant/test/events_index.test.js
  node/ai-knowledge-assistant/test/http_index.test.js
Labels: javascript

#318 fix: env
  node/ai-knowledge-assistant/env.js
Labels: javascript

#319 feat: Consolidate dialogs and contact-form-app code samples to enable inclusions into the dialogs guide
  apps-script/contact-form-app/main.gs
  apps-script/dialogs/README.md
  apps-script/dialogs/appsscript.json
  apps-script/dialogs/dialogs.gs
Labels: javascript

#320 feat: add region tags for guide inclusions
  apps-script/contact-form-app/contactForm.gs
  apps-script/contact-form-app/main.gs
Labels: javascript

#322 fix: rollback to two files in the contat-form-app code sample in apps…
  apps-script/contact-form-app/contactForm.gs
  apps-script/contact-form-app/main.gs
Labels: javascript

#323 fix: region tags
  apps-script/contact-form-app/main.gs
  node/contact-form-app/index.js
Labels: javascript

#324 feat: fix bugs and implement Python for contact-form-app
  apps-script/contact-form-app/main.gs
  node/contact-form-app/index.js
  python/contact-form-app/.gcloudignore
  python/contact-form-app/README.md
  python/contact-form-app/app.yaml
  python/contact-form-app/main.py
  python/contact-form-app/requirements.txt
Labels: python

#325 feat: remove obsolete code samples
  java/basic-async-app/README.md
  java/basic-async-app/pom.xml
  java/basic-async-app/src/main/appengine/app.yaml
  java/basic-async-app/src/main/java/com/google/chat/app/basic/async/App.java
  java/basic-async-app/src/main/resources/application.properties
  java/basic-async-app/src/main/resources/service-acct.json
  java/card-app/README.md
  java/card-app/pom.xml
  java/card-app/src/main/appengine/app.yaml
  java/card-app/src/main/java/com/google/chat/card/App.java
  python/basic-async-app/.gcloudignore
  python/basic-async-app/README.md
  python/basic-async-app/app.yaml
  python/basic-async-app/main.py
  python/basic-async-app/requirements.txt
  python/basic-async-app/service-acct.json
  python/basic-async-app/templates/home.html
  python/card-app/.gcloudignore
  python/card-app/README.md
  python/card-app/app.yaml
  python/card-app/main.py
  python/card-app/requirements.txt
  python/card-app/templates/home.html
Labels: python

#326 feat: remove obsolete code sample node/basic-cloud-functions-bot
  node/basic-cloud-functions-bot/README.md
  node/basic-cloud-functions-bot/index.js
  node/basic-cloud-functions-bot/package-lock.json
  node/basic-cloud-functions-bot/package.json
Labels: javascript

#327 feat: add contact-form-app in Java
  java/contact-form-app/.gcloudignore
  java/contact-form-app/README.md
  java/contact-form-app/pom.xml
  java/contact-form-app/src/main/appengine/app.yaml
  java/contact-form-app/src/main/java/com/google/chat/contact/App.java
  java/contact-form-app/src/main/resources/applicaton.properties
Labels: java

#329 feat: improve readavility of Java samples
  java/app-home/pom.xml
  java/app-home/src/main/java/com/google/chat/app/home/App.java
  java/avatar-app/pom.xml
  java/avatar-app/src/main/java/App.java
  java/basic-app/pom.xml
  java/basic-app/src/main/java/com/google/chat/app/basic/App.java
  java/contact-form-app/src/main/java/com/google/chat/contact/App.java
  java/preview-link/pom.xml
  java/preview-link/src/main/java/com/google/chat/preview/App.java
  java/pub-sub-app/src/main/java/Main.java
  java/vote-app/pom.xml
  java/vote-app/src/main/java/com/google/chat/app/vote/App.java
  java/webhook/src/main/java/com/google/chat/webhook/App.java
Labels: java

#330 feat: upgrade the selection input code sample in apps script
  apps-script/selection-input/README.md
  apps-script/selection-input/on-widget-update.gs
  apps-script/selection-input/selection-input.gs
Labels: javascript

#332 fix: region tag
  python/selection-input/main.py
Labels: python

#333 feat: refresh code sample READMEs
  README.md
  apps-script/contact-form-app/README.md
  apps-script/selection-input/README.md
  apps-script/vote-app/README.md
  apps-script/webhook/README.md
  java/pub-sub-app/README.md
  java/selection-input/README.md
  java/vote-app/README.md
  java/webhook/README.md
  node/pub-sub-app/README.md
  node/selection-input/README.md
  node/vote-app/README.md
  node/webhook/README.md
  python/auth-app/README.md
  python/pub-sub-app/README.md
  python/selection-input/README.md
  python/vote-app/README.md
  python/webhook/README.md
Labels: markdown

#335 fix: README images
  java/vote-app/README.md
  node/vote-app/README.md
  python/vote-app/README.md
Labels: markdown
