Repository googleworkspace/google-chat-samples, pull requests merged in 2025-05, with the labels that each got.

#362 feat: upgrade close dialog code snippets
  apps-script/contact-form-app/main.gs
  java/contact-form-app/src/main/java/com/google/chat/contact/App.java
  node/contact-form-app/index.js
  python/contact-form-app/main.py
Labels: javascript

#365 fix: Upgrade Ubuntu to supported version
  .github/workflows/publish.yml
Labels: yaml

#363 fix: resolve logger warnings
  python/auth-app/auth.py
Labels: python
